version: '3'

dotenv: ['.env']

vars:
  IMAGE_BASE: nuxt3-app
  VERSION:
    sh: "jq -r .version package.json"
  IMAGE_TAG: "{{.IMAGE_BASE}}:v{{.VERSION}}"
  DEV_CONTAINER_NAME: nuxt3-dev
  PROD_CONTAINER_NAME: nuxt3-prod
  PORT: '{{ default "3000" .PORT }}'

tasks:
  default:
    desc: Показать текущую версию проекта из package.json и список доступных команд
    silent: true
    cmds:
      - "echo 📦 Версия проекта: v{{.VERSION}}"
      - echo ""
      - echo "📋 Доступные команды:"
      - echo "  task dev     🔧 Запуск в режиме разработки (hot-reload)"
      - echo "  task prod    🚀 Сборка и запуск в продакшене"
      - echo "  task build   🛠 Только сборка продакшн-образа"
      - echo "  task         📦 Показать эту справку"

  show:
    desc: Выводит список переменных
    silent: true
    cmds:
      - "echo 📦 VERSION: {{.VERSION}}"
      - "echo 🐳 IMAGE_TAG: {{.IMAGE_TAG}}"
      - "echo 🚪 PORT: {{.PORT}}"
      - "echo 📁 DEV_CONTAINER_NAME: {{.DEV_CONTAINER_NAME}}"
      - "echo 📁 PROD_CONTAINER_NAME: {{.PROD_CONTAINER_NAME}}"

  build-image:
    desc: Умная сборка":" buildx если есть, иначе BuildKit
    silent: true
    cmds:
      - |
        if docker buildx version >/dev/null 2>&1; then
          echo "🛠 Используется buildx"
          docker buildx build --load -t {{.IMAGE_TAG}} --target {{.TARGET}} .
        else
          echo "🛠 Используется обычный build с BuildKit"
          DOCKER_BUILDKIT=1 docker build -t {{.IMAGE_TAG}} --target {{.TARGET}} .
        fi

  dev:
    desc: Запуск Nuxt 3 в режиме разработки (hot reload)
    vars:
      TARGET: development
    cmds:
      - echo "🧹 Удаляем старый dev-контейнер (если был)..."
      - docker rm -f {{.DEV_CONTAINER_NAME}} || true
      - task: build-image
        vars:
          TARGET: "{{.TARGET}}"
      - echo "🚀 Запуск контейнера для разработки..."
      - docker run -d --name {{.DEV_CONTAINER_NAME}} -p {{.PORT}}:3000 -v .:/app -v /app/node_modules -v /app/.nuxt -v /app/.data {{.IMAGE_TAG}}
      - lazydocker
      - docker stop {{.DEV_CONTAINER_NAME}}

  prod:
    desc: Сборка и запуск Nuxt 3 в продакшене
    vars:
      TARGET: production
    cmds:
      - echo "🧹 Удаляем старый prod-контейнер (если был)..."
      - docker rm -f {{.PROD_CONTAINER_NAME}} || true
      - task: build-image
        vars:
          TARGET: "{{.TARGET}}"
      - echo "🚀 Запуск контейнера для продакшена..."
      - docker run -d --name {{.PROD_CONTAINER_NAME}} -p {{.PORT}}:3000 {{.IMAGE_TAG}}
      - lazydocker
      - docker stop {{.DEV_CONTAINER_NAME}}

  build:
    desc: Только сборка Nuxt 3 для продакшена
    vars:
      TARGET: production
    cmds:
      - task: build-image

  test:
    desc: Запуск unit-тестов внутри контейнера
    vars:
      TARGET: development
    cmds:
      - echo "🧪 Сборка контейнера для тестов..."
      - task: build-image
      - echo "🚀 Запуск тестов в контейнере..."
      - docker run --rm -v .:/app -v /app/node_modules {{.IMAGE_TAG}} sh -c "npm install && npm run test"
  release:
    desc: 📦 Релиз (major|minor|patch). Фиксация, слияние в release, пуш.
    silent: true
    cmds:
      - |
        if ! echo "{{.CLI_ARGS}}" | grep -q -- "--yes"; then
          echo "❌ Добавь --yes для подтверждения релиза (пример: task release minor --yes)"
          exit 1
        fi

        PART=$(echo "{{.CLI_ARGS}}" | awk '{print $1}')
        if ! echo "$PART" | grep -qE '^(major|minor|patch)$'; then
          echo "❌ Первый аргумент должен быть 'major', 'minor' или 'patch'"
          exit 1
        fi

        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

        # Проверка на незакоммиченные изменения
        if [ -n "$(git status --porcelain)" ]; then
          echo "📝 Есть незакоммиченные изменения. Фиксируем..."
          git add .
          git commit -m "[Общее] Фиксация для релиза"
        fi

        echo "📦 Текущая версия: $(jq -r .version package.json)"

        # Обновление версии
        VERSION=$(jq -r '.version' package.json)
        MAJOR=$(echo "$VERSION" | cut -d. -f1)
        MINOR=$(echo "$VERSION" | cut -d. -f2)
        PATCH=$(echo "$VERSION" | cut -d. -f3)

        if [ "$PART" = "major" ]; then
          MAJOR=$((MAJOR + 1))
          MINOR=0
          PATCH=0
        elif [ "$PART" = "minor" ]; then
          MINOR=$((MINOR + 1))
          PATCH=0
        elif [ "$PART" = "patch" ]; then
          PATCH=$((PATCH + 1))
        fi

        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        jq --arg v "$NEW_VERSION" '.version = $v' package.json > package.tmp.json && mv package.tmp.json package.json
        git add package.json
        git commit -m "[Общее] Обновление версии: $VERSION → $NEW_VERSION"

        echo "🔀 Переключаемся на ветку release..."
        git fetch origin
        git checkout release
        git pull origin release

        echo "🔁 Вливаем изменения из $CURRENT_BRANCH в release..."
        git merge "$CURRENT_BRANCH" --no-ff -m "[Общее] Релиз из ветки $CURRENT_BRANCH"

        echo "📤 Пуш в origin release..."
        git push origin release

        echo "↩️ Возврат на ветку $CURRENT_BRANCH"
        git checkout "$CURRENT_BRANCH"

        echo "✅ Релиз завершён: $VERSION → $NEW_VERSION"
