version: '3'

dotenv: ['.env']

vars:
  IMAGE_BASE: nuxt3-app
  VERSION:
    sh: "jq -r .version package.json"
  IMAGE_TAG: "{{.IMAGE_BASE}}:v{{.VERSION}}"
  DEV_CONTAINER_NAME: nuxt3-dev
  PROD_CONTAINER_NAME: nuxt3-prod
  PORT: '{{ default "3000" .PORT }}'


tasks:
  default:
    desc: Показать текущую версию проекта из package.json и список доступных команд
    silent: true
    cmds:
      - "echo 📦 Версия проекта: v{{.VERSION}}"
      - echo ""
      - echo "📋 Доступные команды:"
      - echo "  task dev     🔧 Запуск в режиме разработки (hot-reload)"
      - echo "  task prod    🚀 Сборка и запуск в продакшене"
      - echo "  task build   🛠 Только сборка продакшн-образа"
      - echo "  task         📦 Показать эту справку"
  show:
    desk: Выводит список переменных
    silent: true
    cmds:
      - "echo 📦 VERSION: {{.VERSION}}"
      - "echo 🐳 IMAGE_TAG: {{.IMAGE_TAG}}"
      - "echo 🚪 PORT: {{.PORT}}"
      - "echo 📁 DEV_CONTAINER_NAME: {{.DEV_CONTAINER_NAME}}"
      - "echo 📁 PROD_CONTAINER_NAME: {{.PROD_CONTAINER_NAME}}"
  dev:
    desc: Запуск Nuxt 3 в режиме разработки (hot reload)
    cmds:
      - echo "🧹 Удаляем старый dev-контейнер (если был)..."
      - docker rm -f {{.DEV_CONTAINER_NAME}} || true
      - echo "🐳 Сборка контейнера {{.IMAGE_TAG}} для разработки..."
      - docker build -t {{.IMAGE_TAG}} --target development .
      - echo "🚀 Запуск контейнера для разработки..."
      - docker run -d --name {{.DEV_CONTAINER_NAME}} -p {{.PORT}}:3000 -v .:/app -v /app/node_modules  -v /app/.nuxt  -v /app/.data {{.IMAGE_TAG}}
      - lazydocker
      - docker stop {{.DEV_CONTAINER_NAME}}
  prod:
    desc: Сборка и запуск Nuxt 3 в продакшене
    cmds:
      - echo "🧹 Удаляем старый prod-контейнер (если был)..."
      - docker rm -f {{.PROD_CONTAINER_NAME}} || true
      - echo "🐳 Сборка контейнера {{.IMAGE_TAG}} для продакшена..."
      - docker build -t {{.IMAGE_TAG}} --target production .
      - echo "🚀 Запуск контейнера для продакшена..."
      - docker run -d --name {{.PROD_CONTAINER_NAME}} -p {{.PORT}}:3000 {{.IMAGE_TAG}}
      - lazydocker
      - docker stop {{.DEV_CONTAINER_NAME}}
  build:
    desc: Только сборка Nuxt 3 для продакшена
    cmds:
      - echo "🐳 Сборка контейнера {{.IMAGE_TAG}} (production)..."
      - docker build -t {{.IMAGE_TAG}} --target production .

  test:
    desc: Запуск unit-тестов внутри контейнера
    cmds:
      - echo "🧪 Сборка контейнера для тестов..."
      - docker build -t {{.IMAGE_TAG}} --target development .
      - echo "🚀 Запуск тестов в контейнере..."
      - docker run --rm -v .:/app -v /app/node_modules {{.IMAGE_TAG}} sh -c "npm install && npm run test"